### ISSUE TITLE
(low priority, not critical) \n introduced in the merge #7078, breaking the line when zpool status while rebuilding

### ISSUE THREAD

**Issue by carlesmateo** [thegreatgazoo/zfs#10]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | N/A
Distribution Version    | N/A
Linux Kernel                 | N/A
Architecture                 | Any
ZFS Version                  | DRAID #7078 pull request
SPL Version                  | N/A

### Describe the problem you're observing
While Rebuilding zpool status breaks a line with carriage return.
It is a \n.
So you get the message for the amount rebuilt (i.e. 85.1G) and time to go in two lines (, 0 days 00:29:51 to go):
```
  scan: rebuild in progress since Tue Feb  6 15:39:16 2018
              1.83T scanned at 1.78G/s, 851G issued at 2.63G/s, 5.43T total
              85.1G rebuilt, 15.32% done
, 0 days 00:29:51 to go
```

![2018-02-06 15-40-24-draid-slash-n-to-go](https://user-images.githubusercontent.com/2362025/35868645-0546e9bc-0b55-11e8-83f2-c026559eb454.png)

### Describe how to reproduce the problem
Launch a dRAID Rebuild and type zpool status

### Include any warning/errors/backtraces from the system logs
Example:
```
  scan: rebuild in progress since Tue Feb  6 15:39:16 2018
	1.83T scanned at 1.78G/s, 851G issued at 2.63G/s, 5.43T total
	85.1G rebuilt, 15.32% done
, 0 days 00:29:51 to go
```

**Comment by thegreatgazoo** [comment]
Fixed by latest commit. Please reopen if it's still there.
