### ISSUE TITLE
draid replace routine?

### ISSUE THREAD

**Issue by kbuggenhout** [thegreatgazoo/zfs#6]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  CentOS
Distribution Version    |  7.3
Linux Kernel                 |  3.10.0-514.26.2.el7
Architecture                 |  x86 64 bit
ZFS Version                  |  0.7.0-rc3
SPL Version                  |  0.7.0-rc5

### Describe the problem you're observing

creating a draid2 vdev on 4 drives works like a charm
but when I do the test offline 1 drive , the spare kicks in as expected.
when I online the drive again it does not free the spare

when I remove the drive from the pool, ( zpool detach tank sdc) and use 
zpool replace -f tank '$draid2-0-s0' sdc  it does its job, but now I am running without a spare.

guess I should not detach the drive from the pool.

### Describe how to reproduce the problem

see above... offline a drive then detach and replace the spare with that free drive

### Include any warning/errors/backtraces from the system logs

no warnings or errors, fs still online

**Comment by thegreatgazoo** [comment]
Let's say sda has failed, and replaced by _$draid2-0-s0_. Now normally what the admin would do is to replace the failed sda with a new drive, using zpool replace. Once that's done, the _$draid2-0-s0_ will become available again.

In your case, the offline drive came back online again, if the drive is again healthy, you can simple detach the _$draid2-0-s0_. That'd make the dspare available again, which essentially undo the rebuild.

**Comment by kbuggenhout** [comment]
will try again failing a drive by disconnecting it logically, then after sync build bring it back in, do the replace drive procedure, and see how it reacts... thnx..

any idea if this is getting merged into the tree some day?

**Comment by thegreatgazoo** [comment]
Please try with the latest code zfsonlinux#7078
